MediaOrganiser/Models/ErrorViewModel.cs
using System;

namespace MediaOrganiser.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MediaOrganiser/Models/MediaFile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaOrganiser.Models
{
    public class MediaFile
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string Type { get; set; }
        public string Comments { get; set; }
    }
}

MediaOrganiser/Models/OrganiserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaOrganiser.Models
{
    public class OrganiserModel
    {
        public List<MediaFile> FileList { get; set; }
    }
}

MediaOrganiser/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MediaOrganiser.Models;
using Newtonsoft.Json;
using System.Text;

namespace MediaOrganiser.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var model = new OrganiserModel();

            if (HttpContext.Session.TryGetValue("_files", out var files))
            {
                model.FileList = JsonConvert.DeserializeObject<List<MediaFile>>(Encoding.ASCII.GetString(files));
            }
            else
            {
                model.FileList = new List<MediaFile>
                {
                    new MediaFile{Id = 1, FileName = "Cerys", Path = "C:\\files", Type = ".fag", Comments = "Totally a fag"}
                };
                HttpContext.Session.Set("_files", Encoding.ASCII.GetBytes(JsonConvert.SerializeObject(model.FileList)));
            }

            return View("index", model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MediaOrganiser/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MediaOrganiser.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MediaOrganiser.Controllers
{
    public class MediaController : Controller
    {
        // GET: Media/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Media/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                List<MediaFile> files = null;
                if (!HttpContext.Session.TryGetValue("_files", out var filesBytes))
                {
                    files = new List<MediaFile>();
                }
                else
                {
                    files = JsonConvert.DeserializeObject<List<MediaFile>>(Encoding.ASCII.GetString(filesBytes));
                }

                files.Add(new MediaFile
                {
                    Id = files.Count + 1,
                    FileName = collection["FileName"],
                    Path = collection["Path"],
                    Type = collection["Type"],
                    Comments = collection["Comments"]
                });

                HttpContext.Session.Set("_files", Encoding.ASCII.GetBytes(JsonConvert.SerializeObject(files)));

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Media/Edit/filename
        public ActionResult Edit(int id)
        {
            MediaFile file = null;
            if (HttpContext.Session.TryGetValue("_files", out var filesBytes))
            {
                var files = JsonConvert.DeserializeObject<List<MediaFile>>(Encoding.ASCII.GetString(filesBytes));
                file = files.SingleOrDefault(x => x.Id == id);
            }

            return View("Edit", file);
        }

        // POST: Media/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                if (!HttpContext.Session.TryGetValue("_files", out var filesBytes))
                {
                    return Edit(id);
                }
                var files = JsonConvert.DeserializeObject<List<MediaFile>>(Encoding.ASCII.GetString(filesBytes));
                var file = files.SingleOrDefault(x => x.Id == id);

                file.FileName = collection["FileName"];
                file.Path = collection["Path"];
                file.Type = collection["Type"];
                file.Comments = collection["Comments"];

                HttpContext.Session.Set("_files", Encoding.ASCII.GetBytes(JsonConvert.SerializeObject(files)));

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return Edit(id);
            }
        }

        // GET: Media/Delete/5
        public ActionResult Delete(int id)
        {
            if (!HttpContext.Session.TryGetValue("_files", out var filesBytes))
            {
                return RedirectToAction("Index", "Home");
            }
            var files = JsonConvert.DeserializeObject<List<MediaFile>>(Encoding.ASCII.GetString(filesBytes));
            var file = files.SingleOrDefault(x => x.Id == id);

            return View("Delete", file);
        }

        // POST: Media/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                if (!HttpContext.Session.TryGetValue("_files", out var filesBytes))
                {
                    return Delete(id);
                }
                var files = JsonConvert.DeserializeObject<List<MediaFile>>(Encoding.ASCII.GetString(filesBytes));
                var file = files.SingleOrDefault(x => x.Id == id);

                files.Remove(file);

                HttpContext.Session.Set("_files", Encoding.ASCII.GetBytes(JsonConvert.SerializeObject(files)));

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return Delete(id);
            }
        }
    }
}

MediaOrganiser/Views/Home/Index.cshtml
@model OrganiserModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

@{
    if (Model.FileList == null)
    {
        <h4>Load settings to begin</h4>
    }
    else
    {
        @Html.Partial("List", Model.FileList)
    }
}

MediaOrganiser/Views/Home/List.cshtml
@model IEnumerable<MediaOrganiser.Models.MediaFile>

<p>
    <a asp-controller="Media" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comments)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Path)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comments)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Media", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", "Media", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

MediaOrganiser/Views/Media/Create.cshtml
@model MediaOrganiser.Models.MediaFile

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MediaFile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FileName" class="control-label"></label>
                <input asp-for="FileName" class="form-control" />
                <span asp-validation-for="FileName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input asp-for="Path" class="form-control" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MediaOrganiser/Views/Media/Delete.cshtml
@model MediaOrganiser.Models.MediaFile

@{
    ViewData["Title"] = "Delete";
    ViewBag.FileName = Model.FileName;
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MediaFile</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MediaOrganiser/Views/Media/Edit.cshtml
@model MediaOrganiser.Models.MediaFile

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MediaFile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FileName" class="control-label"></label>
                <input asp-for="FileName" class="form-control" />
                <span asp-validation-for="FileName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input asp-for="Path" class="form-control" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MediaOrganiser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediaOrganiser</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MediaOrganiser</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MediaOrganiser - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>